---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: archives
spec:
  selector:
    matchLabels:
      app: archives
  template:
    metadata:
      labels:
        app: archives
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: archives
          image: shokohsc/moleculer-ouistity
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: APP_GLOBAL_GATEWAY_URL
              value: http://api.svc.cluster.local
            - name: APP_RETHINKDB_HOSTNAME
              value: rethinkdb
            - name: APP_NATS_HOSTNAME
              value: nats
            - name: APP_RABBITMQ_HOSTNAME
              value: rabbitmq
            - name: APP_RABBITMQ_USERNAME
              value: rabbitmq
            - name: APP_RABBITMQ_PASSWORD
              value: changeme
            - name: APP_REDIS_HOSTNAME
              value: redis
          args:
            - services/archives.service.js
          resources:
            requests:
              cpu: 10m
              memory: 128M
            limits:
              cpu: 500m
              memory: 128M
          volumeMounts:
            - name: temp
              mountPath: /tmp
      volumes:
        - name: temp
          emptyDir:
            medium: Memory
